# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD-Development

on:
  push:
    branches: [develop]

jobs:
  Development:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Deploy to Digital Ocean
        uses: actions/setup-node@v2
        with:
          # command: bash deploy.sh
          host: ${{secrets.SSH_HOST}} #IP address of the server
          port: ${{secrets.SSH_PORT}} #server PORT
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          script: sh deploy.sh
