name: CI/CD DEVELOP

on:
  push:
    branches: [develop]
  pull_request:
    branches: [ develop ]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: actions/setup-node@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}} 
          port: ${{secrets.SSH_PORT}} 
          script: sh KapiPay/deploy.sh
