name: CI/CD DEVELOP

on:
  push:
    branches: [develop]
      
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: actions/setup-node@v2
  CD:
    needs: [CI]
    runs-on: self-hosted
    steps:
      - name: Update develop branch
        run: git pull

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: test
        run: ls -la
         
         
 

             

