name: CI/CD DEVELOP

on:
  push:
    branches: [develop]
  pull_request:
    branches: [ develop ]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: actions/setup-node@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:   
       - name: Setup SSH
        # You may pin to the exact commit or the version.
        # uses: kielabokkie/ssh-key-and-known-hosts-action@e5c88dc608851beb90a7a78c7d5d2ef6f62f9860
         uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
         with:
          # Private key required to access the host
          ssh-private-key: ${{secrets.KEY}}
          # Hostname or IP to add to the known hosts file
          ssh-host: ${{secrets.HOST}}
          shell: bash KapiPay/deploy.sh
          # Port for key-scanning the server
         # ssh-port: # optional
              
              #//////
              # - name: executing remote ssh commands using ssh key
        # uses: appleboy/ssh-action@master
       # uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      #  with:
         # host: ${{secrets.HOST}}
         # user: ${{secrets.USERNAME}}
         # key: ${{secrets.KEY}} 
          # port: ${{secrets.PORT}} 
         # script: sh KapiPay/deploy.sh
         
 

             

