name: CI/CD DEVELOP

on:
  push:
    branches: [develop]
      
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - name: Checkout Branch        
        uses: actions/checkout@v2 
      
  CD:
    needs: [CI]
    runs-on: self-hosted
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
    
    
    
    #steps:
     # - name: Setup Node.js
      #  uses: actions/setup-node@v1
       # with:
        #  node-version: "14.x"  
      
      - name: Update branch
        run: git pull  
      
      - name: Install dependencies
        run: npm ci
        
      - name: Restart Server
        run: NODE_ENV=development pm2 restart 0 --update-env
        
     #- name: Run bash script
     #  run: git pull    
         
         
 

             

