name: CI/CD Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  #CI:
   # runs-on: ubuntu-latest
    #steps:
     # - name: Deploy
      #  uses: actions/setup-node@v2
  CD:
    #needs: [CI]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
       # ARGS: "-rltgoDzvO" 
       # SOURCE: "dist/"
        REMOTE_HOST: '143.198.188.156'
        REMOTE_USER: 'deploy'
      #  TARGET: ${{ secrets.REMOTE_TARGET }}
      #  EXCLUDE: "/dist/, /node_modules/"
    
    #/////APPLEBOY
    
    #- name: executing remote ssh commands using ssh key
    #  uses: appleboy/ssh-action@master
     # with:
     #   host: '143.198.188.156'
      #  username: 'deploy'
       # key: ${{ secrets.SSH_PRIVATE_KEY }}
       # script: ls -la
       
   # - name: copy file via ssh key
   #   uses: appleboy/scp-action@master
    #  with:
     #   host: ${{ secrets.SSH_HOST_SERVER }}
      #  username: root
       # port: ${{ secrets.SSH_PORT }}
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
       # password: ${{ secrets.SSH_USER_PASSWORD }}
       # source: "tests/a.txt,tests/b.txt"
       # target: ~/
        
        
        #//// GARYGROSSGARTEN
#    - name: Copy folder content recursively to remote
 #     uses: garygrossgarten/github-action-scp@release
  #    with:
   #    local: my-repo
    #   remote: ~/home/deploy
     #  host: '143.198.188.156'
      # port: 22
       #username: deploy
      # password: ${{secrets.SSH_USER_PASSWORD}}
      # privateKey: ${{secrets.SSH_PRIVATE_KEY}}
      # run: ls -la
