name: CI-CD-Production

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Update main branch
      - run: git pull origin main
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Deploy to Digital Ocean
        uses: actions/setup-node@v2
        with:
          command: bash KapiPay deploy.sh
          host: ${{secrets.SSH_HOST}} #IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
