name: CI/CD Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
      
jobs:
  #CI:
   #runs-on: ubuntu-latest
    #steps:
     # - name: Deploy
      #  uses: actions/setup-node@v2
  CD:
    #needs: [CI]
    runs-on: ubuntu-latest
    steps:
     #  //// GARYGROSSGARTEN
     - uses: actions/checkout@v2
     - name: Deploy to Digital Ocean
       uses: garygrossgarten/github-action-ssh@release
       with:
         # command: ls -la
         command: cd KapiPay && bash deploy.sh
         host: ${{ secrets.SSH_HOST_SERVER }}
         username: deploy
         password: ${{ secrets.SSH_USER_PASSWORD }}
         privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
         
      #   local: my-repo
      #   remote: ~/home/deploy
      #   port: 22
      #   password: ${{secrets.SSH_USER_PASSWORD}}
         

      
      
        #/////EASINGTHEMES
#    - name: Deploy to Production server
 #     uses: easingthemes/ssh-deploy@main
  #    env:
   #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
    #    ARGS: "-rltgoDzvO" 
     #   SOURCE: "dist/"
      #  REMOTE_HOST: '143.198.188.156'
       # REMOTE_USER: 'deploy'
      #  TARGET: ${{ secrets.REMOTE_TARGET }}
       # EXCLUDE: "/dist/, /node_modules/"
      
      
      # ////// JIM CRONSQUIST
#      - name: Execute SSH commmands on remote server
 #       uses: JimCronqvist/action-ssh@master
  #      with:
   #       hosts:  "deploy@143.198.188.156:5050"
    #      privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
     #     command: ls -la
    
    #/////APPLEBOY
    
    #- name: executing remote ssh commands using ssh key
    #  uses: appleboy/ssh-action@master
     # with:
     #   host: '143.198.188.156'
      #  username: 'deploy'
       # key: ${{ secrets.SSH_PRIVATE_KEY }}
       # script: ls -la
       
   # - name: copy file via ssh key
   #   uses: appleboy/scp-action@master
    #  with:
     #   host: ${{ secrets.SSH_HOST_SERVER }}
      #  username: root
       # port: ${{ secrets.SSH_PORT }}
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
       # password: ${{ secrets.SSH_USER_PASSWORD }}
       # source: "tests/a.txt,tests/b.txt"
       # target: ~/
        
        

